author: J. Muirhead
params:
  choices:
    - coastwise
    - all_traffic
  scenario:
   - seed_ports1
   - seed_ports2
  sp_name: 
   - hypothetical_sp
   - bal_improvisus
  habitat_threshold:
    - hypothetical_sp: 0.0
    - bal_improvisus: 0.1781
  port_area: 1.0e+07
  max_density_individuals: 5.0e+3
  fw_reduction: 0.0
  larval_dev_lag: 604800
  juvenile_lag: 86400
  mature_lag: 5184000
  repro_lag: 1209600
  ship_port_prob: 1.0
  port_comptency_prob: 1.0
  boot_iter: 1
  effective_wsa_scale: 0.1
